### PR TITLE
Automagical features

### PR DESCRIPTION
**Pull request by beefcat666**
* Automatically reapply monitor clamp whenever the display is awakened from sleep. This is a workaround for an NVIDIA bug that causes the setting to be ignored after Windows puts the display to sleep on some hardware configurations.

* Automatically disable the clamp when HDR is turned on in Windows, and re-enable when HDR is turned off. (Win+Alt+B users rejoice). Resolves issue #4 .

* Minimize to tray feature, allowing the above features to operate quietly in the background. Resolves issue #16

### CODE REVIEW

**Comment by ledoge** [comment]
Very cool stuff, thanks! I'll take a closer look and see if I can figure out how to match up the data from that API you're using to check if HDR is enabled with the NVAPI data sometime soon.

**Comment by Acaki** [comment]
Hi @beefcat666 very good work! I built the code on your branch and it seems to work fine.

One small question, is it possible to detect HDR status for individual monitor? I asked because Win+Alt+B toggles HDR mode on all monitors, but usually I only wanted to enable it for my main one, so currently I just use the windows display settings to toggle HDR for main display instead of pressing Win+Alt+B, but that doesn't seem to be detected by the program.

Thanks for your work anyway!

**Comment by beefcat666** [comment]
I'll investigate the sleep issue.

Detecting per-monitor HDR status is something I would like to do but have not implemented. Doing this requires either getting the HDR status from the NVAPI, or finding a way to match monitor data gathered from NVAPI and the Windows API. I only have one HDR capable monitor at the moment so I haven't been able  to experiment much here.

**Comment by ledoge** [comment]
Check out the `features` branch I just pushed – HDR is now detected properly per monitor, and the config now also keeps track of whether the user had the clamp enabled or not. Additionally, the clamp is automatically re-applied on startup and on any display config changes, and that includes proper handling of HDR. So if HDR was toggled the application wasn't running, the next time it's started it'll either disable the color space conversion (if HDR is active) or re-apply it (if it's not).

That state handling was a pain to get working properly, so there might still be some bugs left, but it seems to handle every case I tested fine on my machine at least.

Regarding the sleep issue: Not sure how exactly to test for it, as it doesn't seem to happen on my setup, but I commented the code out for now. My new code for re-applying the clamp on display config changes might take care of that issue anyway though?

**Comment by ledoge** [comment]
I pushed a release without the sleep code for now to gather some feedback on the HDR part. If you can figure out what was causing the crash (and the code is actually needed still), I'll add it back in.

**Pull request merged**
